from rest_framework import routers
from customer_app.views import CustomerViewset
from django.urls import path, include

router = routers.SimpleRouter()

try:
    # Registering the 'customer' route with the CustomerViewset
    router.register(r"customer", CustomerViewset, basename="customer")
except Exception as e:
    # Handle and log any registration exceptions
    raise e

urlpatterns = []

try:
    # Including the URLs generated by the router
    urlpatterns.append(path("", include(router.urls), name="customer"))
except Exception as e:
    # Handle and log any inclusion exceptions
    raise e
